mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
  mapperLocations: classpath:mybatis/*Mapper.xml

server:
  port: 8080

spring:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800
  application:
    name:
      DayCare
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
    password: csye6200
    url: jdbc:mysql://39.108.233.164:3308/daycare?useUnicode=true&character_set_server=utf8mb4&useSSL=false
    username: neu
  resources:
    static-locations: classpath:/static/,classpath:/templates/

mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: false
